env:
  global:
    - secure: "uq/iCCaRumHIOPfTzl2s/mRSPpViIwZkS4jaWVqUymg8gqXTV7iOzOGu3FJVTtCo3bkDath8HdoXtoaUmiWKPhbf4iZ6CBrytk38SEX6R3NNn+lbBjSuYYPXzgVzi9S/uNspPIJcK3DyqS9tXBwNIVLKFI20CvwHYn5BD4vDaZjxE7YsCWTaM+E0g1aM11DL485UwPRCGE/99DAwagFd0XoOQCTv/3RNNfhDbEm/wWevgjhdsmC/Wy/uqT/XnXRcAZel/0OByjj0DX8Dc67sFtScra+a+doePGWbg2m6Jl7r6GWx15/QNCBukTQTz1rDnLGzq+yflDGqTomSMGQRvys5lyFK6z8RYyrdy4vasvbg88EfEMWjbFdiC6MnsoMK5fp9tEcAHy6gExlmuBKe33gKwBtrEdb8OiAAmrB0OQIaPQEsfwZXu9fPEdpGrs51J5bpx4DiXnlmy445BFm12x6V4fRmV49xZas4RfITZfS1tP7qRa93/GKZMZlI2YFcyaH09/QjZ3PkM3Gj2DHJSBEgfT3ruyyLxprQteGGS0MljY8uxSMSAEdRZAaTi8I4HdEjO/6rqylwxhT2i4NS/bS3b5f/+J4/hUZJCAp7dvHdZ9RmlCZ4XF3vTp/LAvKjcwo8/GPzyD7FsOabtLD7AzQTb8yR5jZ2K7cShAzK5X4="
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.9.1-linux-amd64.tar.gz
    - REPO_DIR=/home/travis/build/sparkfabrik/blackfire-chart
    - CHART_NAME=blackfire

before_install:
  - openssl aes-256-cbc -K $encrypted_fa820de3c082_key -iv $encrypted_fa820de3c082_iv -in .travis/id_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  - mkdir -p /tmp/${CHART_NAME}
  - mkdir -p /tmp/package
  - mkdir -p /tmp/deploy
  - cp -R Chart.yaml values.yaml templates /tmp/blackfire

script:
  - cd /tmp/${CHART_NAME}
  - helm lint
  - helm package . --destination /tmp/package
  - cd /tmp/package
  - helm repo index . --url https://tech.sparkfabrik.com/blackfire-chart/
  - cd /tmp/deploy
  - git init
  - git config user.name ${GH_USER_NAME}
  - git config user.email ${GH_USER_EMAIL}
  - git remote add origin git@github.com:sparkfabrik/blackfire-chart.git
  - git fetch && git checkout gh-pages
  - cp -fR /tmp/package/* .
  - git add .
  - git commit -m "Automatic release build by travis-ci from master ${TRAVIS_COMMIT}"
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then git push -f; fi;
