{{- if and .Values.chromeNode.enabled .Values.chromeNode.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.chromeNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: selenium-chrome-node
    {{- include "selenium.commonLabels" . | nindent 4 }}
  {{- with .Values.chromeNode.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.chromeNode.service.type }}
  selector:
    app: selenium-chrome-node
  ports:
    - name: tcp-chrome
      protocol: TCP
      port: {{ .Values.chromeNode.seleniumServicePort }}
      targetPort: {{ .Values.chromeNode.seleniumPort }}
{{- end }}
