apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blackfire.fullname" . }}
  labels: {{- include "blackfire.labels" . | nindent 4 }}
type: Opaque
data:
  server_id: {{ required "serverId is required" .Values.serverId }}
  server_token: {{ required "serverToken is required" .Values.serverToken }}
