apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "blackfire.fullname" . }}
  labels:
    app: {{ template "blackfire.name" . }}
    chart: {{ template "blackfire.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "blackfire.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "blackfire.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BLACKFIRE_SERVER_ID
              {{- if .Values.blackfire.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.blackfire.existingSecret }}
                  key: server_id
              {{- else }}
              value: {{ .Values.blackfire.server_id }}
              {{- end }}
            - name: BLACKFIRE_SERVER_TOKEN
              {{- if .Values.blackfire.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.blackfire.existingSecret }}
                  key: server_token
              {{- else }}
              value: {{ .Values.blackfire.server_token }}
              {{- end }}
            - name: BLACKFIRE_LOG_LEVEL
              value: {{ default "1" .Values.blackfire.log_level }}
          ports:
            - name: agent
              containerPort: 8707
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: agent
          readinessProbe:
            tcpSocket:
              port: agent
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
